Remove the CentOS 6 builder (for now?)
M2Crypto fails to install in CentOS 6 due to the older version of swig.

```
swig -python -D__x86_64__ -I/usr/include/python2.6 -I/usr/include \
  -I/usr/include/openssl -includeall -modern -builtin
  -outdir build/lib.linux-x86_64-2.6/M2Crypto \
  -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i

    swig error : Unrecognized option -builtin
    Use 'swig -help' for available options.
    error: command 'swig' failed with exit status 1

$ rpm -q swig
swig-1.3.40-6.el6.x86_64
```